# Generated by Django 4.1.7 on 2023-04-04 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='haircutting',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manicure',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pedicure',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='styling',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='threading',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='waxing',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='shopapointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
