# Generated by Django 4.1.7 on 2023-03-31 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salonName', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('haircutting', models.BooleanField(default=False, null=True)),
                ('Styling', models.BooleanField(default=False, null=True)),
                ('Threading', models.BooleanField(default=False, null=True)),
                ('Waxing', models.BooleanField(default=False, null=True)),
                ('Manicure', models.BooleanField(default=False, null=True)),
                ('Pedicure', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(default='', upload_to='shopImage')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
