# Generated by Django 4.1.7 on 2023-04-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_employee_haircutting_alter_employee_manicure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='haircutting',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manicure',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pedicure',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='styling',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='threading',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='waxing',
        ),
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.CharField(default='', max_length=100),
        ),
    ]
