# Generated by Django 4.1.7 on 2023-04-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_service_remove_employee_services_employee_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='services',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.CharField(default='', max_length=100),
        ),
    ]
